print "Seeding..."

user01 = User.create(username: "Shu", password: "123")
user02 = User.create(username: "Argoo", password: "123")

card01 = Card.create(user_id: user01.id, name: "Alakazam", image: "https://images.pokemontcg.io/base1/1_hires.png", owned: false, quantity: 0, notes: "")
card02 = Card.create(user_id: user01.id, name: "Blastoise", image: "https://images.pokemontcg.io/base1/2_hires.png", owned: true, quantity: 0, notes: "")
card03 = Card.create(user_id: user01.id, name: "Chansey", image: "https://images.pokemontcg.io/base1/3_hires.png", owned: false, quantity: 0, notes: "")
card04 = Card.create(user_id: user01.id, name: "Charizard", image: "https://images.pokemontcg.io/base1/4_hires.png", owned: true, quantity: 0, notes: "")
card05 = Card.create(user_id: user01.id, name: "Clefairy", image: "https://images.pokemontcg.io/base1/5_hires.png", owned: false, quantity: 0, notes: "")
card06 = Card.create(user_id: user01.id, name: "Gyarados", image: "https://images.pokemontcg.io/base1/6_hires.png", owned: true, quantity: 0, notes: "")
card07 = Card.create(user_id: user01.id, name: "Hitmonchan", image: "https://images.pokemontcg.io/base1/7_hires.png", owned: false, quantity: 0, notes: "")
card08 = Card.create(user_id: user01.id, name: "Machamp", image: "https://images.pokemontcg.io/base1/8_hires.png", owned: true, quantity: 0, notes: "")
card09 = Card.create(user_id: user01.id, name: "Magneton", image: "https://images.pokemontcg.io/base1/9_hires.png", owned: false, quantity: 0, notes: "")
card10 = Card.create(user_id: user01.id, name: "Mewtwo", image: "https://images.pokemontcg.io/base1/10_hires.png", owned: true, quantity: 0, notes: "")
card11 = Card.create(user_id: user01.id, name: "Nidoking", image: "https://images.pokemontcg.io/base1/11_hires.png", owned: false, quantity: 0, notes: "")
card12 = Card.create(user_id: user01.id, name: "Ninetales", image: "https://images.pokemontcg.io/base1/12_hires.png", owned: true, quantity: 0, notes: "")
card13 = Card.create(user_id: user01.id, name: "Poliwrath", image: "https://images.pokemontcg.io/base1/13_hires.png", owned: false, quantity: 0, notes: "")
card14 = Card.create(user_id: user01.id, name: "Raichu", image: "https://images.pokemontcg.io/base1/14_hires.png", owned: true, quantity: 0, notes: "")
card15 = Card.create(user_id: user01.id, name: "Venusaur", image: "https://images.pokemontcg.io/base1/15_hires.png", owned: false, quantity: 0, notes: "")
card16 = Card.create(user_id: user01.id, name: "Zapdos", image: "https://images.pokemontcg.io/base1/16_hires.png", owned: true, quantity: 0, notes: "")

card17 = Card.create(user_id: user02.id, name: "Alakazam", image: "https://images.pokemontcg.io/base1/1_hires.png", owned: true, quantity: 0, notes: "")
card18 = Card.create(user_id: user02.id, name: "Blastoise", image: "https://images.pokemontcg.io/base1/2_hires.png", owned: false, quantity: 0, notes: "")
card19 = Card.create(user_id: user02.id, name: "Chansey", image: "https://images.pokemontcg.io/base1/3_hires.png", owned: true, quantity: 0, notes: "")
card20 = Card.create(user_id: user02.id, name: "Charizard", image: "https://images.pokemontcg.io/base1/4_hires.png", owned: false, quantity: 0, notes: "")
card21 = Card.create(user_id: user02.id, name: "Clefairy", image: "https://images.pokemontcg.io/base1/5_hires.png", owned: true, quantity: 0, notes: "")
card22 = Card.create(user_id: user02.id, name: "Gyarados", image: "https://images.pokemontcg.io/base1/6_hires.png", owned: false, quantity: 0, notes: "")
card23 = Card.create(user_id: user02.id, name: "Hitmonchan", image: "https://images.pokemontcg.io/base1/7_hires.png", owned: true, quantity: 0, notes: "")
card24 = Card.create(user_id: user02.id, name: "Machamp", image: "https://images.pokemontcg.io/base1/8_hires.png", owned: false, quantity: 0, notes: "")
card25 = Card.create(user_id: user02.id, name: "Magneton", image: "https://images.pokemontcg.io/base1/9_hires.png", owned: true, quantity: 0, notes: "")
card26 = Card.create(user_id: user02.id, name: "Mewtwo", image: "https://images.pokemontcg.io/base1/10_hires.png", owned: false, quantity: 0, notes: "")
card27 = Card.create(user_id: user02.id, name: "Nidoking", image: "https://images.pokemontcg.io/base1/11_hires.png", owned: true, quantity: 0, notes: "")
card28 = Card.create(user_id: user02.id, name: "Ninetales", image: "https://images.pokemontcg.io/base1/12_hires.png", owned: false, quantity: 0, notes: "")
card29 = Card.create(user_id: user02.id, name: "Poliwrath", image: "https://images.pokemontcg.io/base1/13_hires.png", owned: true, quantity: 0, notes: "")
card30 = Card.create(user_id: user02.id, name: "Raichu", image: "https://images.pokemontcg.io/base1/14_hires.png", owned: false, quantity: 0, notes: "")
card31 = Card.create(user_id: user02.id, name: "Venusaur", image: "https://images.pokemontcg.io/base1/15_hires.png", owned: true, quantity: 0, notes: "")
card32 = Card.create(user_id: user02.id, name: "Zapdos", image: "https://images.pokemontcg.io/base1/16_hires.png", owned: false, quantity: 0, notes: "")

print "Done!"