print "Seeding..."

user01 = User.create(username: "Shu", password: "123")
user02 = User.create(username: "Test", password: "test")

# Base Set
card01 = Card.create(user_id: user01.id, name: "Alakazam", card_number: 1, set: "Base Set", image: "https://images.pokemontcg.io/base1/1_hires.png", quantity: 3, rarity: "holo", notes: "Non-shadowless, NM condition for all.")
card02 = Card.create(user_id: user01.id, name: "Blastoise", card_number: 2, set: "Base Set", image: "https://images.pokemontcg.io/base1/2_hires.png", quantity: 3, rarity: "holo", notes: "Non-shadowless, one stage-error, NM condition.")
card03 = Card.create(user_id: user01.id, name: "Chansey", card_number: 3, set: "Base Set", image: "https://images.pokemontcg.io/base1/3_hires.png", quantity: 7, rarity: "holo", notes: "One shadowless, one damaged (crease), rest shadowed and fine.")
card04 = Card.create(user_id: user01.id, name: "Charizard", card_number: 4, set: "Base Set", image: "https://images.pokemontcg.io/base1/4_hires.png", quantity: 2, rarity: "holo", notes: "Not for trade yet.")
card05 = Card.create(user_id: user01.id, name: "Clefairy", card_number: 5, set: "Base Set", image: "https://images.pokemontcg.io/base1/5_hires.png", quantity: 3, rarity: "holo", notes: "Need a second SHADOWED one, two shadowless for sale but not great conditions.")
card06 = Card.create(user_id: user01.id, name: "Gyarados", card_number: 6, set: "Base Set", image: "https://images.pokemontcg.io/base1/6_hires.png", quantity: 3, rarity: "holo", notes: "Shadowed, NM condition.")
card07 = Card.create(user_id: user01.id, name: "Hitmonchan", card_number: 7, set: "Base Set", image: "https://images.pokemontcg.io/base1/7_hires.png", quantity: 4, rarity: "holo", notes: "One shadowless, first edition LP condition. Rest shadowed.")
card08 = Card.create(user_id: user01.id, name: "Machamp", card_number: 8, set: "Base Set", image: "https://images.pokemontcg.io/base1/8_hires.png", quantity: 4, rarity: "holo", notes: "One shadowless, one not for trade due to sentimental value, two shadowed.")
card09 = Card.create(user_id: user01.id, name: "Magneton", card_number: 9, set: "Base Set", image: "https://images.pokemontcg.io/base1/9_hires.png", quantity: 6, rarity: "holo", notes: "One shadowless first edition not for trade, rest shadowed for trade, NM condition.")
card10 = Card.create(user_id: user01.id, name: "Mewtwo", card_number: 10, set: "Base Set", image: "https://images.pokemontcg.io/base1/10_hires.png", quantity: 2, rarity: "holo", notes: "Shadowed.")
card11 = Card.create(user_id: user01.id, name: "Nidoking", card_number: 11, set: "Base Set", image: "https://images.pokemontcg.io/base1/11_hires.png", quantity: 4, rarity: "holo", notes: "Two shadowless for trade, MP condition.")
card12 = Card.create(user_id: user01.id, name: "Ninetales", card_number: 12, set: "Base Set", image: "https://images.pokemontcg.io/base1/12_hires.png", quantity: 4, rarity: "holo", notes: "One shadowless for trade, LP condition. One shadowed, MP/damaged")
card13 = Card.create(user_id: user01.id, name: "Poliwrath", card_number: 13, set: "Base Set", image: "https://images.pokemontcg.io/base1/13_hires.png", quantity: 3, rarity: "holo", notes: "Two Shadowed, one shadowless not for trade.")
card14 = Card.create(user_id: user01.id, name: "Raichu", card_number: 14, set: "Base Set", image: "https://images.pokemontcg.io/base1/14_hires.png", quantity: 2, rarity: "holo", notes: "Shadowed.")
card15 = Card.create(user_id: user01.id, name: "Venusaur", card_number: 15, set: "Base Set", image: "https://images.pokemontcg.io/base1/15_hires.png", quantity: 3, rarity: "holo", notes: "One shadowed with blue splotch error for trade, others reg shadowed.")
card16 = Card.create(user_id: user01.id, name: "Zapdos", card_number: 16, set: "Base Set", image: "https://images.pokemontcg.io/base1/16_hires.png", quantity: 2, rarity: "holo", notes: "Shadowed.")
card397 = Card.create(user_id: user01.id, name: "Beedrill", card_number: 17, set: "Base Set", image: "https://images.pokemontcg.io/base1/17_hires.png", quantity: 0, rarity: "rare", notes: "")
card398 = Card.create(user_id: user01.id, name: "Dragonair", card_number: 18, set: "Base Set", image: "https://images.pokemontcg.io/base1/18_hires.png", quantity: 0, rarity: "rare", notes: "")
card399 = Card.create(user_id: user01.id, name: "Dugtrio", card_number: 19, set: "Base Set", image: "https://images.pokemontcg.io/base1/19_hires.png", quantity: 0, rarity: "rare", notes: "")
card400 = Card.create(user_id: user01.id, name: "Electabuzz", card_number: 20, set: "Base Set", image: "https://images.pokemontcg.io/base1/20_hires.png", quantity: 0, rarity: "rare", notes: "")
card401 = Card.create(user_id: user01.id, name: "Electrode", card_number: 21, set: "Base Set", image: "https://images.pokemontcg.io/base1/21_hires.png", quantity: 0, rarity: "rare", notes: "")
card402 = Card.create(user_id: user01.id, name: "Pidgeotto", card_number: 22, set: "Base Set", image: "https://images.pokemontcg.io/base1/22_hires.png", quantity: 0, rarity: "rare", notes: "")

# Jungle
card17 = Card.create(user_id: user01.id, name: "Clefable", card_number: 1, set: "Jungle", image: "https://images.pokemontcg.io/base2/1_hires.png", quantity: 4, rarity: "holo", notes: "One damaged one with no symbol, one MP, rest normal.")
card18 = Card.create(user_id: user01.id, name: "Electrode", card_number: 2, set: "Jungle", image: "https://images.pokemontcg.io/base2/2_hires.png", quantity: 4, rarity: "holo", notes: "One first edition for sale")
card19 = Card.create(user_id: user01.id, name: "Flareon", card_number: 3, set: "Jungle", image: "https://images.pokemontcg.io/base2/3_hires.png", quantity: 2, rarity: "holo", notes: "Need third")
card20 = Card.create(user_id: user01.id, name: "Jolteon", card_number: 4, set: "Jungle", image: "https://images.pokemontcg.io/base2/4_hires.png", quantity: 3, rarity: "holo", notes: "One with small surface damage, might trade for better one.")
card21 = Card.create(user_id: user01.id, name: "Kangaskhan", card_number: 5, set: "Jungle", image: "https://images.pokemontcg.io/base2/5_hires.png", quantity: 4, rarity: "holo", notes: "Want to sell one.")
card22 = Card.create(user_id: user01.id, name: "Mr. Mime", card_number: 6, set: "Jungle", image: "https://images.pokemontcg.io/base2/6_hires.png", quantity: 2, rarity: "holo", notes: "Need third.")
card23 = Card.create(user_id: user01.id, name: "Nidoqueen", card_number: 7, set: "Jungle", image: "https://images.pokemontcg.io/base2/7_hires.png", quantity: 2, rarity: "holo", notes: "Not for sale.")
card24 = Card.create(user_id: user01.id, name: "Pidgeot", card_number: 8, set: "Jungle", image: "https://images.pokemontcg.io/base2/8_hires.png", quantity: 2, rarity: "holo", notes: "Might need one with better looks.")
card25 = Card.create(user_id: user01.id, name: "Pinsir", card_number: 9, set: "Jungle", image: "https://images.pokemontcg.io/base2/9_hires.png", quantity: 3, rarity: "holo", notes: "One first edition for sale, need to replace with normal one.")
card26 = Card.create(user_id: user01.id, name: "Scyther", card_number: 10, set: "Jungle", image: "https://images.pokemontcg.io/base2/10_hires.png", quantity: 2, rarity: "holo", notes: "Not for sale")
card27 = Card.create(user_id: user01.id, name: "Snorlax", card_number: 11, set: "Jungle", image: "https://images.pokemontcg.io/base2/11_hires.png", quantity: 3, rarity: "holo", notes: "Two first editions for sale, need to replace with normals.")
card28 = Card.create(user_id: user01.id, name: "Vaporeon", card_number: 12, set: "Jungle", image: "https://images.pokemontcg.io/base2/12_hires.png", quantity: 3, rarity: "holo", notes: "Might need one with better looks/less scratching.")
card29 = Card.create(user_id: user01.id, name: "Venomoth", card_number: 13, set: "Jungle", image: "https://images.pokemontcg.io/base2/13_hires.png", quantity: 3, rarity: "holo", notes: "Fine.")
card30 = Card.create(user_id: user01.id, name: "Victreebel", card_number: 14, set: "Jungle", image: "https://images.pokemontcg.io/base2/14_hires.png", quantity: 3, rarity: "holo", notes: "Fine.")
card31 = Card.create(user_id: user01.id, name: "Vileplume", card_number: 15, set: "Jungle", image: "https://images.pokemontcg.io/base2/15_hires.png", quantity: 4, rarity: "holo", notes: "One first edition for sale.")
card32 = Card.create(user_id: user01.id, name: "Wigglytuff", card_number: 16, set: "Jungle", image: "https://images.pokemontcg.io/base2/16_hires.png", quantity:4, rarity: "holo", notes: "Might need one with fewer scratches, have one with surface damage for sale.")

# Fossil
card33 = Card.create(user_id: user01.id, name: "Aerodactyl", card_number: 1, set: "Fossil", image: "https://images.pokemontcg.io/base3/1_hires.png", quantity: 4, rarity: "holo", notes: "Have pre-release one for sale.")
card34 = Card.create(user_id: user01.id, name: "Articuno", card_number: 2, set: "Fossil", image: "https://images.pokemontcg.io/base3/2_hires.png", quantity: 3, rarity: "holo", notes: "Might want one with fewer scratches, but expensive.")
card35 = Card.create(user_id: user01.id, name: "Ditto", card_number: 3, set: "Fossil", image: "https://images.pokemontcg.io/base3/3_hires.png", quantity: 4, rarity: "holo", notes: "One first edition for sale.")
card36 = Card.create(user_id: user01.id, name: "Dragonite", card_number: 4, set: "Fossil", image: "https://images.pokemontcg.io/base3/4_hires.png", quantity: 3, rarity: "holo", notes: "Fine.")
card37 = Card.create(user_id: user01.id, name: "Gengar", card_number: 5, set: "Fossil", image: "https://images.pokemontcg.io/base3/5_hires.png", quantity: 3, rarity: "holo", notes: "Have one with a little bit of 'peeling' on the top border for sale.")
card38 = Card.create(user_id: user01.id, name: "Haunter", card_number: 6, set: "Fossil", image: "https://images.pokemontcg.io/base3/6_hires.png", quantity: 3, rarity: "holo", notes: "Fine.")
card39 = Card.create(user_id: user01.id, name: "Hitmonlee", card_number: 7, set: "Fossil", image: "https://images.pokemontcg.io/base3/7_hires.png", quantity: 3, rarity: "holo", notes: "Fine.")
card40 = Card.create(user_id: user01.id, name: "Hypno", card_number: 8, set: "Fossil", image: "https://images.pokemontcg.io/base3/8_hires.png", quantity: 3, rarity: "holo", notes: "Fine conditions.")
card41 = Card.create(user_id: user01.id, name: "Kabutops", card_number: 9, set: "Fossil", image: "https://images.pokemontcg.io/base3/9_hires.png", quantity: 3, rarity: "holo", notes: "Nice.")
card42 = Card.create(user_id: user01.id, name: "Lapras", card_number: 10, set: "Fossil", image: "https://images.pokemontcg.io/base3/10_hires.png", quantity: 4, rarity: "holo", notes: "One for sale, LP.")
card43 = Card.create(user_id: user01.id, name: "Magneton", card_number: 11, set: "Fossil", image: "https://images.pokemontcg.io/base3/11_hires.png", quantity: 3, rarity: "holo", notes: "One with fewer scratches wanted.")
card44 = Card.create(user_id: user01.id, name: "Moltres", card_number: 12, set: "Fossil", image: "https://images.pokemontcg.io/base3/12_hires.png", quantity: 3, rarity: "holo", notes: "Fine conditions, might want one more.")
card45 = Card.create(user_id: user01.id, name: "Muk", card_number: 13, set: "Fossil", image: "https://images.pokemontcg.io/base3/13_hires.png", quantity: 4, rarity: "holo", notes: "One for sale.")
card46 = Card.create(user_id: user01.id, name: "Raichu", card_number: 14, set: "Fossil", image: "https://images.pokemontcg.io/base3/14_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card47 = Card.create(user_id: user01.id, name: "Zapdos", card_number: 15, set: "Fossil", image: "https://images.pokemontcg.io/base3/15_hires.png", quantity: 3, rarity: "holo", notes: "Might be interested in cosmo-foil one.")

# Base Set 2
card48 = Card.create(user_id: user01.id, name: "Alakazam", card_number: 1, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/1_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more if I go through with three of each bs2 holos.")
card49 = Card.create(user_id: user01.id, name: "Blastoise", card_number: 2, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/2_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more but is expensive.")
card50 = Card.create(user_id: user01.id, name: "Chansey", card_number: 3, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/3_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more.")
card51 = Card.create(user_id: user01.id, name: "Charizard", card_number: 4, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/4_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more but is expensive.")
card52 = Card.create(user_id: user01.id, name: "Clefable", card_number: 5, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/5_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more.")
card53 = Card.create(user_id: user01.id, name: "Clefairy", card_number: 6, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/6_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card54 = Card.create(user_id: user01.id, name: "Gyarados", card_number: 7, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/7_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card55 = Card.create(user_id: user01.id, name: "Hitmonchan", card_number: 8, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/8_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more.")
card56 = Card.create(user_id: user01.id, name: "Magneton", card_number: 9, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/9_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card57 = Card.create(user_id: user01.id, name: "Mewtwo", card_number: 10, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/10_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card58 = Card.create(user_id: user01.id, name: "Nidoking", card_number: 11, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/11_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more.")
card59 = Card.create(user_id: user01.id, name: "Nidoqueen", card_number: 12, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/12_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card60 = Card.create(user_id: user01.id, name: "Ninetales", card_number: 13, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/13_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card61 = Card.create(user_id: user01.id, name: "Pidgeot", card_number: 14, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/14_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card62 = Card.create(user_id: user01.id, name: "Poliwrath", card_number: 15, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/15_hires.png", quantity: 4, rarity: "holo", notes: "Two with blue spot errors!")
card63 = Card.create(user_id: user01.id, name: "Raichu", card_number: 16, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/16_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more.")
card64 = Card.create(user_id: user01.id, name: "Scyther", card_number: 17, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/17_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more.")
card65 = Card.create(user_id: user01.id, name: "Venusaur", card_number: 18, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/18_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more but is expensive.")
card66 = Card.create(user_id: user01.id, name: "Wigglytuff", card_number: 19, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/19_hires.png", quantity: 2, rarity: "holo", notes: "Need 1 more.")
card67 = Card.create(user_id: user01.id, name: "Zapdos", card_number: 20, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/20_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more if I decide.")

# Team Rocket
card68 = Card.create(user_id: user01.id, name: "Dark Alakazam", card_number: 1, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/1_hires.png", quantity: 4, rarity: "holo", notes: "Need 1st Edition, one NM and one slightly damaged one for sale (corner).")
card69 = Card.create(user_id: user01.id, name: "Dark Arbok", card_number: 2, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/2_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card70 = Card.create(user_id: user01.id, name: "Dark Blastoise", card_number: 3, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/3_hires.png", quantity: 1, rarity: "holo", notes: "Need 1st Edition and regular.")
card71 = Card.create(user_id: user01.id, name: "Dark Charizard", card_number: 4, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/4_hires.png", quantity: 1, rarity: "holo", notes: "Need 1st Edition and regular.")
card72 = Card.create(user_id: user01.id, name: "Dark Dragonite", card_number: 5, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/5_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card73 = Card.create(user_id: user01.id, name: "Dark Dugtrio", card_number: 6, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/6_hires.png", quantity: 4, rarity: "holo", notes: "One for sale.")
card74 = Card.create(user_id: user01.id, name: "Dark Golbat", card_number: 7, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/7_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card75 = Card.create(user_id: user01.id, name: "Dark Gyarados", card_number: 8, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/8_hires.png", quantity: 6, rarity: "holo", notes: "Two for sale, and one pre-release maybe.")
card76 = Card.create(user_id: user01.id, name: "Dark Hypno", card_number: 9, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/9_hires.png", quantity: 4, rarity: "holo", notes: "One for sale.")
card77 = Card.create(user_id: user01.id, name: "Dark Machamp", card_number: 10, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/10_hires.png", quantity: 4, rarity: "holo", notes: "One for sale.")
card78 = Card.create(user_id: user01.id, name: "Dark Magneton", card_number: 11, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/11_hires.png", quantity: 2, rarity: "holo", notes: "Need one regular.")
card79 = Card.create(user_id: user01.id, name: "Dark Slowbro", card_number: 12, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/12_hires.png", quantity: 4, rarity: "holo", notes: "One for sale.")
card80 = Card.create(user_id: user01.id, name: "Dark Vileplume", card_number: 13, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/13_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card81 = Card.create(user_id: user01.id, name: "Dark Weezing", card_number: 14, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/14_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card82 = Card.create(user_id: user01.id, name: "Here Comes Team Rocket!", card_number: 15, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/15_hires.png", quantity: 2, rarity: "holo", notes: "Need one regular.")
card83 = Card.create(user_id: user01.id, name: "Rocket's Sneak Attack", card_number: 16, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/16_hires.png", quantity: 2, rarity: "holo", notes: "Need 1st Edition.")
card84 = Card.create(user_id: user01.id, name: "Rainbow Energy", card_number: 17, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/17_hires.png", quantity: 3, rarity: "holo", notes: "All set.")

# Gym Heroes
card85 = Card.create(user_id: user01.id, name: "Blaine's Moltres", card_number: 1, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/1_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card86 = Card.create(user_id: user01.id, name: "Brock's Rhydon", card_number: 2, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/2_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card87 = Card.create(user_id: user01.id, name: "Erika's Clefable", card_number: 3, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/3_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card88 = Card.create(user_id: user01.id, name: "Erika's Dragonair", card_number: 4, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/4_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card89 = Card.create(user_id: user01.id, name: "Erika's Vileplume", card_number: 5, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/5_hires.png", quantity: 5, rarity: "holo", notes: "Two for sale.")
card90 = Card.create(user_id: user01.id, name: "Lt. Surge's Electabuzz", card_number: 6, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/6_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card91 = Card.create(user_id: user01.id, name: "Lt. Surge's Fearow", card_number: 7, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/7_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card92 = Card.create(user_id: user01.id, name: "Lt. Surge's Magneton", card_number: 8, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/8_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card93 = Card.create(user_id: user01.id, name: "Misty's Seadra", card_number: 9, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/9_hires.png", quantity: 6, rarity: "holo", notes: "2 prereleases for sale.")
card94 = Card.create(user_id: user01.id, name: "Misty's Tentacruel", card_number: 10, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/10_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card95 = Card.create(user_id: user01.id, name: "Rocket's Hitmonchan", card_number: 11, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/11_hires.png", quantity: 2, rarity: "holo", notes: "Need third one, might replace one scratched one.")
card96 = Card.create(user_id: user01.id, name: "Rocket's Moltres", card_number: 12, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/12_hires.png", quantity: 2, rarity: "holo", notes: "Need third one.")
card97 = Card.create(user_id: user01.id, name: "Rocket's Scyther", card_number: 13, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/13_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card98 = Card.create(user_id: user01.id, name: "Sabrina's Gengar", card_number: 14, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/14_hires.png", quantity: 2, rarity: "holo", notes: "Need third one.")
card99 = Card.create(user_id: user01.id, name: "Brock", card_number: 15, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/15_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card100 = Card.create(user_id: user01.id, name: "Erika", card_number: 16, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/16_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card101 = Card.create(user_id: user01.id, name: "Lt. Surge", card_number: 17, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/17_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card102 = Card.create(user_id: user01.id, name: "Misty", card_number: 18, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/18_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card103 = Card.create(user_id: user01.id, name: "The Rocket's Trap", card_number: 19, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/19_hires.png", quantity: 3, rarity: "holo", notes: "All set.")

# Gym Challenge
card104 = Card.create(user_id: user01.id, name: "Blaine's Arcanine", card_number: 1, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/1_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card105 = Card.create(user_id: user01.id, name: "Blaine's Charizard", card_number: 2, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/2_hires.png", quantity: 1, rarity: "holo", notes: "Need two more, but expensive.")
card106 = Card.create(user_id: user01.id, name: "Brock's Ninetales", card_number: 3, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/3_hires.png", quantity: 2, rarity: "holo", notes: "Need third one.")
card107 = Card.create(user_id: user01.id, name: "Erika's Venusaur", card_number: 4, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/4_hires.png", quantity: 2, rarity: "holo", notes: "Need third one.")
card108 = Card.create(user_id: user01.id, name: "Giovanni's Gyarados", card_number: 5, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/5_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card109 = Card.create(user_id: user01.id, name: "Giovanni's Machamp", card_number: 6, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/6_hires.png", quantity: 2, rarity: "holo", notes: "Need third one.")
card110 = Card.create(user_id: user01.id, name: "Giovanni's Nidoking", card_number: 7, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/7_hires.png", quantity: 2, rarity: "holo", notes: "Need third one.")
card111 = Card.create(user_id: user01.id, name: "Giovanni's Persian", card_number: 8, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/8_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card112 = Card.create(user_id: user01.id, name: "Koga's Beedrill", card_number: 9, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/9_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card113 = Card.create(user_id: user01.id, name: "Koga's Ditto", card_number: 10, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/10_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card114 = Card.create(user_id: user01.id, name: "Lt. Surge's Raichu", card_number: 11, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/11_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card115 = Card.create(user_id: user01.id, name: "Misty's Golduck", card_number: 12, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/12_hires.png", quantity: 3, rarity: "holo", notes: "Need third one.")
card116 = Card.create(user_id: user01.id, name: "Misty's Gyarados", card_number: 13, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/13_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card117 = Card.create(user_id: user01.id, name: "Rocket's Mewtwo", card_number: 14, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/14_hires.png", quantity: 1, rarity: "holo", notes: "Need two more, but expensive.")
card118 = Card.create(user_id: user01.id, name: "Rocket's Zapdos", card_number: 15, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/15_hires.png", quantity: 2, rarity: "holo", notes: "One first edition for sale, need two regular ones.")
card119 = Card.create(user_id: user01.id, name: "Sabrina's Alakazam", card_number: 16, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/16_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card120 = Card.create(user_id: user01.id, name: "Blaine", card_number: 17, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/17_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card121 = Card.create(user_id: user01.id, name: "Giovanni", card_number: 18, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/18_hires.png", quantity: 3, rarity: "holo", notes: "Need third one.")
card122 = Card.create(user_id: user01.id, name: "Koga", card_number: 19, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/19_hires.png", quantity: 1, rarity: "holo", notes: "Need two more regular ones.")
card123 = Card.create(user_id: user01.id, name: "Sabrina", card_number: 20, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/20_hires.png", quantity: 3, rarity: "holo", notes: "All set.")

# Neo Genesis
card124 = Card.create(user_id: user01.id, name: "Ampharos", card_number: 1, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/1_hires.png", quantity: 1, rarity: "holo", notes: "Only have one in first edition, want to sell/trade for regular ones.")
card125 = Card.create(user_id: user01.id, name: "Azumarill", card_number: 2, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/2_hires.png", quantity: 3, rarity: "holo", notes: "Have one in first edition and one creased one, want to sell/trade for regular ones.")
card126 = Card.create(user_id: user01.id, name: "Bellossom", card_number: 3, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/3_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card127 = Card.create(user_id: user01.id, name: "Feraligatr", card_number: 4, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/4_hires.png", quantity: 2, rarity: "holo", notes: "Have one in first edition, want to sell/trade for regular ones.")
card128 = Card.create(user_id: user01.id, name: "Feraligatr", card_number: 5, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/5_hires.png", quantity: 1, rarity: "holo", notes: "Need two more, but expensive.")
card129 = Card.create(user_id: user01.id, name: "Heracross", card_number: 6, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/6_hires.png", quantity: 2, rarity: "holo", notes: "One first edition for sale/trade for two regular ones.")
card130 = Card.create(user_id: user01.id, name: "Jumpluff", card_number: 7, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/7_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card131 = Card.create(user_id: user01.id, name: "Kingdra", card_number: 8, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/8_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card132 = Card.create(user_id: user01.id, name: "Lugia", card_number: 9, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/9_hires.png", quantity: 1, rarity: "holo", notes: "Need 2 more, but expensive.")
card133 = Card.create(user_id: user01.id, name: "Meganium", card_number: 10, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/10_hires.png", quantity: 2, rarity: "holo", notes: "One first edition for sale/trade for two regular ones.")
card134 = Card.create(user_id: user01.id, name: "Meganium", card_number: 11, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/11_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card135 = Card.create(user_id: user01.id, name: "Pichu", card_number: 12, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/12_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card136 = Card.create(user_id: user01.id, name: "Skarmory", card_number: 13, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/13_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card137 = Card.create(user_id: user01.id, name: "Slowking", card_number: 14, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/14_hires.png", quantity: 3, rarity: "holo", notes: "One might need replacing due to damaged corner?")
card138 = Card.create(user_id: user01.id, name: "Steelix", card_number: 15, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/15_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card139 = Card.create(user_id: user01.id, name: "Togetic", card_number: 16, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/16_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card140 = Card.create(user_id: user01.id, name: "Typhlosion", card_number: 17, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/17_hires.png", quantity: 1, rarity: "holo", notes: "Need two more, but expensive af.")
card141 = Card.create(user_id: user01.id, name: "Typhlosion", card_number: 18, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/18_hires.png", quantity: 2, rarity: "holo", notes: "One first edition, want to sell/trade for two regular ones.")
card142 = Card.create(user_id: user01.id, name: "Metal Energy", card_number: 19, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/19_hires.png", quantity: 3, rarity: "holo", notes: "All set.")

# Neo Discovery
card143 = Card.create(user_id: user01.id, name: "Espeon", card_number: 1, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/1_hires.png", quantity: 1, rarity: "holo", notes: "Need two more, but might be expensive.")
card144 = Card.create(user_id: user01.id, name: "Forretress", card_number: 2, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/2_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card143 = Card.create(user_id: user01.id, name: "Hitmontop", card_number: 3, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/3_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card144 = Card.create(user_id: user01.id, name: "Houndoom", card_number: 4, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/4_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card145 = Card.create(user_id: user01.id, name: "Houndour", card_number: 5, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/5_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card146 = Card.create(user_id: user01.id, name: "Kabutops", card_number: 6, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/6_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card147 = Card.create(user_id: user01.id, name: "Magnemite", card_number: 7, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/7_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card148 = Card.create(user_id: user01.id, name: "Politoed", card_number: 8, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/8_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card149 = Card.create(user_id: user01.id, name: "Poliwrath", card_number: 9, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/9_hires.png", quantity: 1, rarity: "holo", notes: "Need two more, especially after the last time.")
card150 = Card.create(user_id: user01.id, name: "Scizor", card_number: 10, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/10_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card151 = Card.create(user_id: user01.id, name: "Smeargle", card_number: 11, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/11_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card152 = Card.create(user_id: user01.id, name: "Tyranitar", card_number: 12, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/12_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card153 = Card.create(user_id: user01.id, name: "Umbreon", card_number: 13, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/13_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card154 = Card.create(user_id: user01.id, name: "Unown A", card_number: 14, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/14_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card155 = Card.create(user_id: user01.id, name: "Ursaring", card_number: 15, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/15_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card156 = Card.create(user_id: user01.id, name: "Wobbuffet", card_number: 16, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/16_hires.png", quantity: 2, rarity: "holo", notes: "One creased for sale, one normal.")
card157 = Card.create(user_id: user01.id, name: "Yanma", card_number: 17, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/17_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")

# Neo Revelations
card158 = Card.create(user_id: user01.id, name: "Ampharos", card_number: 1, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/1_hires.png", quantity:0, rarity: "holo", notes: "Need any and all!")
card159 = Card.create(user_id: user01.id, name: "Blissey", card_number: 2, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/2_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card160 = Card.create(user_id: user01.id, name: "Celebi", card_number: 3, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/3_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card161 = Card.create(user_id: user01.id, name: "Crobat", card_number: 4, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/4_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card162 = Card.create(user_id: user01.id, name: "Delibird", card_number: 5, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/5_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card163 = Card.create(user_id: user01.id, name: "Entei", card_number: 6, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/6_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card164 = Card.create(user_id: user01.id, name: "Ho-oh", card_number: 7, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/7_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card165 = Card.create(user_id: user01.id, name: "Houndoom", card_number: 8, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/8_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card166 = Card.create(user_id: user01.id, name: "Jumpluff", card_number: 9, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/9_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card167 = Card.create(user_id: user01.id, name: "Magneton", card_number: 10, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/10_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card168 = Card.create(user_id: user01.id, name: "Misdreavus", card_number: 11, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/11_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card169 = Card.create(user_id: user01.id, name: "Porygon2", card_number: 12, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/12_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card170 = Card.create(user_id: user01.id, name: "Raikou", card_number: 13, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/13_hires.png", quantity: 2, rarity: "holo", notes: "Need one more, but might be expensive.")
card171 = Card.create(user_id: user01.id, name: "Suicune", card_number: 14, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/14_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card172 = Card.create(user_id: user01.id, name: "Shining Gyarados", card_number: 65, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/65_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will be VERY expensive.")
card173 = Card.create(user_id: user01.id, name: "Shining Magikarp", card_number: 66, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/66_hires.png", quantity: 1, rarity: "holo", notes: "Only have one but it's first edition, want to sell/ttrade for normals.")

# Neo Destiny
card174 = Card.create(user_id: user01.id, name: "Dark Ampharos", card_number: 1, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/1_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card175 = Card.create(user_id: user01.id, name: "Dark Crobat", card_number: 2, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/2_hires.png", quantity: 1, rarity: "holo", notes: "Have only first edition, want to sell/trade for three regulars")
card176 = Card.create(user_id: user01.id, name: "Dark Donphan", card_number: 3, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/3_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card177 = Card.create(user_id: user01.id, name: "Dark Espeon", card_number: 4, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/4_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card178 = Card.create(user_id: user01.id, name: "Dark Feraligatr", card_number: 5, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/5_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card179 = Card.create(user_id: user01.id, name: "Dark Gengar", card_number: 6, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/6_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card180 = Card.create(user_id: user01.id, name: "Dark Houndoom", card_number: 7, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/7_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card181 = Card.create(user_id: user01.id, name: "Dark Porygon2", card_number: 8, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/8_hires.png", quantity: 2, rarity: "holo", notes: "One with a big scratch for sale, one normal.")
card182 = Card.create(user_id: user01.id, name: "Dark Scizor", card_number: 9, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/9_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card183 = Card.create(user_id: user01.id, name: "Dark Typhlosion", card_number: 10, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/10_hires.png", quantity: 3, rarity: "holo", notes: "All set.")
card184 = Card.create(user_id: user01.id, name: "Dark Tyranitar", card_number: 11, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/11_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all!")
card185 = Card.create(user_id: user01.id, name: "Light Arcanine", card_number: 12, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/12_hires.png", quantity: 1, rarity: "holo", notes: "Need two more but might be expensive.")
card186 = Card.create(user_id: user01.id, name: "Light Azumarill", card_number: 13, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/13_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card187 = Card.create(user_id: user01.id, name: "Light Dragonite", card_number: 14, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/14_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card188 = Card.create(user_id: user01.id, name: "Light Togetic", card_number: 15, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/15_hires.png", quantity: 1, rarity: "holo", notes: "Need two more.")
card189 = Card.create(user_id: user01.id, name: "Miracle Energy", card_number: 16, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/16_hires.png", quantity: 2, rarity: "holo", notes: "Need one more.")
card190 = Card.create(user_id: user01.id, name: "Shining Celebi", card_number: 106, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/106_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card191 = Card.create(user_id: user01.id, name: "Shining Charizard", card_number: 107, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/107_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card192 = Card.create(user_id: user01.id, name: "Shining Kabutops", card_number: 108, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/108_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card193 = Card.create(user_id: user01.id, name: "Shining Mewtwo", card_number: 109, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/109_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card194 = Card.create(user_id: user01.id, name: "Shining Noctowl", card_number: 110, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/110_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card195 = Card.create(user_id: user01.id, name: "Shining Raichu", card_number: 111, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/111_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card196 = Card.create(user_id: user01.id, name: "Shining Steelix", card_number: 112, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/112_hires.png", quantity: 0, rarity: "holo", notes: "Need any and all, but will definitely be expensive.")
card197 = Card.create(user_id: user01.id, name: "Shining Tyranitar", card_number: 113, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/113_hires.png", quantity: 1, rarity: "holo", notes: "Need any and all!")

# TEST USER

# Base Set
card198 = Card.create(user_id: user02.id, name: "Alakazam", card_number: 1, set: "Base Set", image: "https://images.pokemontcg.io/base1/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card199 = Card.create(user_id: user02.id, name: "Blastoise", card_number: 2, set: "Base Set", image: "https://images.pokemontcg.io/base1/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card200 = Card.create(user_id: user02.id, name: "Chansey", card_number: 3, set: "Base Set", image: "https://images.pokemontcg.io/base1/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card201 = Card.create(user_id: user02.id, name: "Charizard", card_number: 4, set: "Base Set", image: "https://images.pokemontcg.io/base1/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card202 = Card.create(user_id: user02.id, name: "Clefairy", card_number: 5, set: "Base Set", image: "https://images.pokemontcg.io/base1/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card203 = Card.create(user_id: user02.id, name: "Gyarados", card_number: 6, set: "Base Set", image: "https://images.pokemontcg.io/base1/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card204 = Card.create(user_id: user02.id, name: "Hitmonchan", card_number: 7, set: "Base Set", image: "https://images.pokemontcg.io/base1/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card205 = Card.create(user_id: user02.id, name: "Machamp", card_number: 8, set: "Base Set", image: "https://images.pokemontcg.io/base1/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card206 = Card.create(user_id: user02.id, name: "Magneton", card_number: 9, set: "Base Set", image: "https://images.pokemontcg.io/base1/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card207 = Card.create(user_id: user02.id, name: "Mewtwo", card_number: 10, set: "Base Set", image: "https://images.pokemontcg.io/base1/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card208 = Card.create(user_id: user02.id, name: "Nidoking", card_number: 11, set: "Base Set", image: "https://images.pokemontcg.io/base1/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card209 = Card.create(user_id: user02.id, name: "Ninetales", card_number: 12, set: "Base Set", image: "https://images.pokemontcg.io/base1/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card210 = Card.create(user_id: user02.id, name: "Poliwrath", card_number: 13, set: "Base Set", image: "https://images.pokemontcg.io/base1/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card211 = Card.create(user_id: user02.id, name: "Raichu", card_number: 14, set: "Base Set", image: "https://images.pokemontcg.io/base1/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card212 = Card.create(user_id: user02.id, name: "Venusaur", card_number: 15, set: "Base Set", image: "https://images.pokemontcg.io/base1/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card213 = Card.create(user_id: user02.id, name: "Zapdos", card_number: 16, set: "Base Set", image: "https://images.pokemontcg.io/base1/16_hires.png", quantity: 0, rarity: "holo", notes: "")

# Jungle
card214 = Card.create(user_id: user02.id, name: "Clefable", card_number: 1, set: "Jungle", image: "https://images.pokemontcg.io/base2/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card215 = Card.create(user_id: user02.id, name: "Electrode", card_number: 2, set: "Jungle", image: "https://images.pokemontcg.io/base2/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card216 = Card.create(user_id: user02.id, name: "Flareon", card_number: 3, set: "Jungle", image: "https://images.pokemontcg.io/base2/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card217 = Card.create(user_id: user02.id, name: "Jolteon", card_number: 4, set: "Jungle", image: "https://images.pokemontcg.io/base2/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card218 = Card.create(user_id: user02.id, name: "Kangaskhan", card_number: 5, set: "Jungle", image: "https://images.pokemontcg.io/base2/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card219 = Card.create(user_id: user02.id, name: "Mr. Mime", card_number: 6, set: "Jungle", image: "https://images.pokemontcg.io/base2/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card220 = Card.create(user_id: user02.id, name: "Nidoqueen", card_number: 7, set: "Jungle", image: "https://images.pokemontcg.io/base2/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card221 = Card.create(user_id: user02.id, name: "Pidgeot", card_number: 8, set: "Jungle", image: "https://images.pokemontcg.io/base2/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card222 = Card.create(user_id: user02.id, name: "Pinsir", card_number: 9, set: "Jungle", image: "https://images.pokemontcg.io/base2/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card223 = Card.create(user_id: user02.id, name: "Scyther", card_number: 10, set: "Jungle", image: "https://images.pokemontcg.io/base2/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card224 = Card.create(user_id: user02.id, name: "Snorlax", card_number: 11, set: "Jungle", image: "https://images.pokemontcg.io/base2/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card225 = Card.create(user_id: user02.id, name: "Vaporeon", card_number: 12, set: "Jungle", image: "https://images.pokemontcg.io/base2/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card226 = Card.create(user_id: user02.id, name: "Venomoth", card_number: 13, set: "Jungle", image: "https://images.pokemontcg.io/base2/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card227 = Card.create(user_id: user02.id, name: "Victreebel", card_number: 14, set: "Jungle", image: "https://images.pokemontcg.io/base2/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card228 = Card.create(user_id: user02.id, name: "Vileplume", card_number: 15, set: "Jungle", image: "https://images.pokemontcg.io/base2/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card229 = Card.create(user_id: user02.id, name: "Wigglytuff", card_number: 16, set: "Jungle", image: "https://images.pokemontcg.io/base2/16_hires.png", quantity: 0, rarity: "holo", notes: "")

# Fossil
card230 = Card.create(user_id: user02.id, name: "Aerodactyl", card_number: 1, set: "Fossil", image: "https://images.pokemontcg.io/base3/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card231 = Card.create(user_id: user02.id, name: "Articuno", card_number: 2, set: "Fossil", image: "https://images.pokemontcg.io/base3/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card232 = Card.create(user_id: user02.id, name: "Ditto", card_number: 3, set: "Fossil", image: "https://images.pokemontcg.io/base3/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card233 = Card.create(user_id: user02.id, name: "Dragonite", card_number: 4, set: "Fossil", image: "https://images.pokemontcg.io/base3/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card234 = Card.create(user_id: user02.id, name: "Gengar", card_number: 5, set: "Fossil", image: "https://images.pokemontcg.io/base3/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card235 = Card.create(user_id: user02.id, name: "Haunter", card_number: 6, set: "Fossil", image: "https://images.pokemontcg.io/base3/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card236 = Card.create(user_id: user02.id, name: "Hitmonlee", card_number: 7, set: "Fossil", image: "https://images.pokemontcg.io/base3/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card237 = Card.create(user_id: user02.id, name: "Hypno", card_number: 8, set: "Fossil", image: "https://images.pokemontcg.io/base3/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card238 = Card.create(user_id: user02.id, name: "Kabutops", card_number: 9, set: "Fossil", image: "https://images.pokemontcg.io/base3/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card239 = Card.create(user_id: user02.id, name: "Lapras", card_number: 10, set: "Fossil", image: "https://images.pokemontcg.io/base3/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card240 = Card.create(user_id: user02.id, name: "Magneton", card_number: 11, set: "Fossil", image: "https://images.pokemontcg.io/base3/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card241 = Card.create(user_id: user02.id, name: "Moltres", card_number: 12, set: "Fossil", image: "https://images.pokemontcg.io/base3/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card242 = Card.create(user_id: user02.id, name: "Muk", card_number: 13, set: "Fossil", image: "https://images.pokemontcg.io/base3/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card243 = Card.create(user_id: user02.id, name: "Raichu", card_number: 14, set: "Fossil", image: "https://images.pokemontcg.io/base3/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card244 = Card.create(user_id: user02.id, name: "Zapdos", card_number: 15, set: "Fossil", image: "https://images.pokemontcg.io/base3/15_hires.png", quantity: 0, rarity: "holo", notes: "")

# Base Set 2
card245 = Card.create(user_id: user02.id, name: "Alakazam", card_number: 1, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card246 = Card.create(user_id: user02.id, name: "Blastoise", card_number: 2, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card247 = Card.create(user_id: user02.id, name: "Chansey", card_number: 3, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card248 = Card.create(user_id: user02.id, name: "Charizard", card_number: 4, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card249 = Card.create(user_id: user02.id, name: "Clefable", card_number: 5, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card250 = Card.create(user_id: user02.id, name: "Clefairy", card_number: 6, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card251 = Card.create(user_id: user02.id, name: "Gyarados", card_number: 7, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card252 = Card.create(user_id: user02.id, name: "Hitmonchan", card_number: 8, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card253 = Card.create(user_id: user02.id, name: "Magneton", card_number: 9, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card254 = Card.create(user_id: user02.id, name: "Mewtwo", card_number: 10, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card255 = Card.create(user_id: user02.id, name: "Nidoking", card_number: 11, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card256 = Card.create(user_id: user02.id, name: "Nidoqueen", card_number: 12, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card257 = Card.create(user_id: user02.id, name: "Ninetales", card_number: 13, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card258 = Card.create(user_id: user02.id, name: "Pidgeot", card_number: 14, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card259 = Card.create(user_id: user02.id, name: "Poliwrath", card_number: 15, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card260 = Card.create(user_id: user02.id, name: "Raichu", card_number: 16, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card261 = Card.create(user_id: user02.id, name: "Scyther", card_number: 17, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/17_hires.png", quantity: 0, rarity: "holo", notes: "")
card262 = Card.create(user_id: user02.id, name: "Venusaur", card_number: 18, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/18_hires.png", quantity: 0, rarity: "holo", notes: "")
card263 = Card.create(user_id: user02.id, name: "Wigglytuff", card_number: 19, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/19_hires.png", quantity: 0, rarity: "holo", notes: "")
card264 = Card.create(user_id: user02.id, name: "Zapdos", card_number: 20, set: "Base Set 2", image: "https://images.pokemontcg.io/base4/20_hires.png", quantity: 0, rarity: "holo", notes: "")

# Team Rocket
card265 = Card.create(user_id: user02.id, name: "Dark Alakazam", card_number: 1, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card266 = Card.create(user_id: user02.id, name: "Dark Arbok", card_number: 2, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card267 = Card.create(user_id: user02.id, name: "Dark Blastoise", card_number: 3, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card268 = Card.create(user_id: user02.id, name: "Dark Charizard", card_number: 4, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card269 = Card.create(user_id: user02.id, name: "Dark Dragonite", card_number: 5, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card270 = Card.create(user_id: user02.id, name: "Dark Dugtrio", card_number: 6, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card271 = Card.create(user_id: user02.id, name: "Dark Golbat", card_number: 7, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card272 = Card.create(user_id: user02.id, name: "Dark Gyarados", card_number: 8, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card273 = Card.create(user_id: user02.id, name: "Dark Hypno", card_number: 9, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card274 = Card.create(user_id: user02.id, name: "Dark Machamp", card_number: 10, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card275 = Card.create(user_id: user02.id, name: "Dark Magneton", card_number: 11, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card276 = Card.create(user_id: user02.id, name: "Dark Slowbro", card_number: 12, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card277 = Card.create(user_id: user02.id, name: "Dark Vileplume", card_number: 13, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card278 = Card.create(user_id: user02.id, name: "Dark Weezing", card_number: 14, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card279 = Card.create(user_id: user02.id, name: "Here Comes Team Rocket!", card_number: 15, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card280 = Card.create(user_id: user02.id, name: "Rocket's Sneak Attack", card_number: 16, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card281 = Card.create(user_id: user02.id, name: "Rainbow Energy", card_number: 17, set: "Team Rocket", image: "https://images.pokemontcg.io/base5/17_hires.png", quantity: 0, rarity: "holo", notes: "")

# Gym Heroes
card282 = Card.create(user_id: user02.id, name: "Blaine's Moltres", card_number: 1, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card283 = Card.create(user_id: user02.id, name: "Brock's Rhydon", card_number: 2, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card284 = Card.create(user_id: user02.id, name: "Erika's Clefable", card_number: 3, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card285 = Card.create(user_id: user02.id, name: "Erika's Dragonair", card_number: 4, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card286 = Card.create(user_id: user02.id, name: "Erika's Vileplume", card_number: 5, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card287 = Card.create(user_id: user02.id, name: "Lt. Surge's Electabuzz", card_number: 6, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card288 = Card.create(user_id: user02.id, name: "Lt. Surge's Fearow", card_number: 7, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card289 = Card.create(user_id: user02.id, name: "Lt. Surge's Magneton", card_number: 8, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card290 = Card.create(user_id: user02.id, name: "Misty's Seadra", card_number: 9, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card291 = Card.create(user_id: user02.id, name: "Misty's Tentacruel", card_number: 10, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card292 = Card.create(user_id: user02.id, name: "Rocket's Hitmonchan", card_number: 11, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card293 = Card.create(user_id: user02.id, name: "Rocket's Moltres", card_number: 12, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card294 = Card.create(user_id: user02.id, name: "Rocket's Scyther", card_number: 13, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card295 = Card.create(user_id: user02.id, name: "Sabrina's Gengar", card_number: 14, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card296 = Card.create(user_id: user02.id, name: "Brock", card_number: 15, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card297 = Card.create(user_id: user02.id, name: "Erika", card_number: 16, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card298 = Card.create(user_id: user02.id, name: "Lt. Surge", card_number: 17, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/17_hires.png", quantity: 0, rarity: "holo", notes: "")
card299 = Card.create(user_id: user02.id, name: "Misty", card_number: 18, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/18_hires.png", quantity: 0, rarity: "holo", notes: "")
card300 = Card.create(user_id: user02.id, name: "The Rocket's Trap", card_number: 19, set: "Gym Heroes", image: "https://images.pokemontcg.io/gym1/19_hires.png", quantity: 0, rarity: "holo", notes: "")

# Gym Challenge
card301 = Card.create(user_id: user02.id, name: "Blaine's Arcanine", card_number: 1, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card302 = Card.create(user_id: user02.id, name: "Blaine's Charizard", card_number: 2, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card303 = Card.create(user_id: user02.id, name: "Brock's Ninetales", card_number: 3, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card304 = Card.create(user_id: user02.id, name: "Erika's Venusaur", card_number: 4, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card305 = Card.create(user_id: user02.id, name: "Giovanni's Gyarados", card_number: 5, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card306 = Card.create(user_id: user02.id, name: "Giovanni's Machamp", card_number: 6, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card307 = Card.create(user_id: user02.id, name: "Giovanni's Nidoking", card_number: 7, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card308 = Card.create(user_id: user02.id, name: "Giovanni's Persian", card_number: 8, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card309 = Card.create(user_id: user02.id, name: "Koga's Beedrill", card_number: 9, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card310 = Card.create(user_id: user02.id, name: "Koga's Ditto", card_number: 10, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card311 = Card.create(user_id: user02.id, name: "Lt. Surge's Raichu", card_number: 11, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card312 = Card.create(user_id: user02.id, name: "Misty's Golduck", card_number: 12, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card313 = Card.create(user_id: user02.id, name: "Misty's Gyarados", card_number: 13, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card314 = Card.create(user_id: user02.id, name: "Rocket's Mewtwo", card_number: 14, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card315 = Card.create(user_id: user02.id, name: "Rocket's Zapdos", card_number: 15, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card316 = Card.create(user_id: user02.id, name: "Sabrina's Alakazam", card_number: 16, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card317 = Card.create(user_id: user02.id, name: "Blaine", card_number: 17, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/17_hires.png", quantity: 0, rarity: "holo", notes: "")
card318 = Card.create(user_id: user02.id, name: "Giovanni", card_number: 18, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/18_hires.png", quantity: 0, rarity: "holo", notes: "")
card319 = Card.create(user_id: user02.id, name: "Koga", card_number: 19, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/19_hires.png", quantity: 0, rarity: "holo", notes: "")
card320 = Card.create(user_id: user02.id, name: "Sabrina", card_number: 20, set: "Gym Challenge", image: "https://images.pokemontcg.io/gym2/20_hires.png", quantity: 0, rarity: "holo", notes: "")

# Neo Genesis
card321 = Card.create(user_id: user02.id, name: "Ampharos", card_number: 1, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card322 = Card.create(user_id: user02.id, name: "Azumarill", card_number: 2, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card323 = Card.create(user_id: user02.id, name: "Bellossom", card_number: 3, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card324 = Card.create(user_id: user02.id, name: "Feraligatr", card_number: 4, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card325 = Card.create(user_id: user02.id, name: "Feraligatr", card_number: 5, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card326 = Card.create(user_id: user02.id, name: "Heracross", card_number: 6, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card327 = Card.create(user_id: user02.id, name: "Jumpluff", card_number: 7, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card328 = Card.create(user_id: user02.id, name: "Kingdra", card_number: 8, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card329 = Card.create(user_id: user02.id, name: "Lugia", card_number: 9, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card330 = Card.create(user_id: user02.id, name: "Meganium", card_number: 10, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card331 = Card.create(user_id: user02.id, name: "Meganium", card_number: 11, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card332 = Card.create(user_id: user02.id, name: "Pichu", card_number: 12, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card333 = Card.create(user_id: user02.id, name: "Skarmory", card_number: 13, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card334 = Card.create(user_id: user02.id, name: "Slowking", card_number: 14, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card335 = Card.create(user_id: user02.id, name: "Steelix", card_number: 15, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card336 = Card.create(user_id: user02.id, name: "Togetic", card_number: 16, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card337 = Card.create(user_id: user02.id, name: "Typhlosion", card_number: 17, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/17_hires.png", quantity: 0, rarity: "holo", notes: "")
card338 = Card.create(user_id: user02.id, name: "Typhlosion", card_number: 18, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/18_hires.png", quantity: 0, rarity: "holo", notes: "")
card339 = Card.create(user_id: user02.id, name: "Metal Energy", card_number: 19, set: "Neo Genesis", image: "https://images.pokemontcg.io/neo1/19_hires.png", quantity: 0, rarity: "holo", notes: "")

# Neo Discovery
card340 = Card.create(user_id: user02.id, name: "Espeon", card_number: 1, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card341 = Card.create(user_id: user02.id, name: "Forretress", card_number: 2, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card342 = Card.create(user_id: user02.id, name: "Hitmontop", card_number: 3, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card343 = Card.create(user_id: user02.id, name: "Houndoom", card_number: 4, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card344 = Card.create(user_id: user02.id, name: "Houndour", card_number: 5, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card345 = Card.create(user_id: user02.id, name: "Kabutops", card_number: 6, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card346 = Card.create(user_id: user02.id, name: "Magnemite", card_number: 7, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card347 = Card.create(user_id: user02.id, name: "Politoed", card_number: 8, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card348 = Card.create(user_id: user02.id, name: "Poliwrath", card_number: 9, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card349 = Card.create(user_id: user02.id, name: "Scizor", card_number: 10, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card350 = Card.create(user_id: user02.id, name: "Smeargle", card_number: 11, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card351 = Card.create(user_id: user02.id, name: "Tyranitar", card_number: 12, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card352 = Card.create(user_id: user02.id, name: "Umbreon", card_number: 13, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card353 = Card.create(user_id: user02.id, name: "Unown A", card_number: 14, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card354 = Card.create(user_id: user02.id, name: "Ursaring", card_number: 15, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card355 = Card.create(user_id: user02.id, name: "Wobbuffet", card_number: 16, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card356 = Card.create(user_id: user02.id, name: "Yanma", card_number: 17, set: "Neo Discovery", image: "https://images.pokemontcg.io/neo2/17_hires.png", quantity: 0, rarity: "holo", notes: "")

# Neo Revelations
card357 = Card.create(user_id: user02.id, name: "Ampharos", card_number: 1, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card358 = Card.create(user_id: user02.id, name: "Blissey", card_number: 2, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card359 = Card.create(user_id: user02.id, name: "Celebi", card_number: 3, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card360 = Card.create(user_id: user02.id, name: "Crobat", card_number: 4, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card361 = Card.create(user_id: user02.id, name: "Delibird", card_number: 5, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card362 = Card.create(user_id: user02.id, name: "Entei", card_number: 6, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card363 = Card.create(user_id: user02.id, name: "Ho-oh", card_number: 7, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card364 = Card.create(user_id: user02.id, name: "Houndoom", card_number: 8, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card365 = Card.create(user_id: user02.id, name: "Jumpluff", card_number: 9, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card366 = Card.create(user_id: user02.id, name: "Magneton", card_number: 10, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card367 = Card.create(user_id: user02.id, name: "Misdreavus", card_number: 11, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card368 = Card.create(user_id: user02.id, name: "Porygon2", card_number: 12, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card369 = Card.create(user_id: user02.id, name: "Raikou", card_number: 13, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card370 = Card.create(user_id: user02.id, name: "Suicune", card_number: 14, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card371 = Card.create(user_id: user02.id, name: "Shining Gyarados", card_number: 65, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/65_hires.png", quantity: 0, rarity: "holo", notes: "")
card372 = Card.create(user_id: user02.id, name: "Shining Magikarp", card_number: 66, set: "Neo Revelations", image: "https://images.pokemontcg.io/neo3/66_hires.png", quantity: 0, rarity: "holo", notes: "")

# Neo Destiny
card373 = Card.create(user_id: user02.id, name: "Dark Ampharos", card_number: 1, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/1_hires.png", quantity: 0, rarity: "holo", notes: "")
card374 = Card.create(user_id: user02.id, name: "Dark Crobat", card_number: 2, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/2_hires.png", quantity: 0, rarity: "holo", notes: "")
card375 = Card.create(user_id: user02.id, name: "Dark Donphan", card_number: 3, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/3_hires.png", quantity: 0, rarity: "holo", notes: "")
card376 = Card.create(user_id: user02.id, name: "Dark Espeon", card_number: 4, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/4_hires.png", quantity: 0, rarity: "holo", notes: "")
card377 = Card.create(user_id: user02.id, name: "Dark Feraligatr", card_number: 5, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/5_hires.png", quantity: 0, rarity: "holo", notes: "")
card378 = Card.create(user_id: user02.id, name: "Dark Gengar", card_number: 6, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/6_hires.png", quantity: 0, rarity: "holo", notes: "")
card379 = Card.create(user_id: user02.id, name: "Dark Houndoom", card_number: 7, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/7_hires.png", quantity: 0, rarity: "holo", notes: "")
card380 = Card.create(user_id: user02.id, name: "Dark Porygon2", card_number: 8, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/8_hires.png", quantity: 0, rarity: "holo", notes: "")
card381 = Card.create(user_id: user02.id, name: "Dark Scizor", card_number: 9, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/9_hires.png", quantity: 0, rarity: "holo", notes: "")
card382 = Card.create(user_id: user02.id, name: "Dark Typhlosion", card_number: 10, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/10_hires.png", quantity: 0, rarity: "holo", notes: "")
card383 = Card.create(user_id: user02.id, name: "Dark Tyranitar", card_number: 11, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/11_hires.png", quantity: 0, rarity: "holo", notes: "")
card384 = Card.create(user_id: user02.id, name: "Light Arcanine", card_number: 12, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/12_hires.png", quantity: 0, rarity: "holo", notes: "")
card385 = Card.create(user_id: user02.id, name: "Light Azumarill", card_number: 13, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/13_hires.png", quantity: 0, rarity: "holo", notes: "")
card386 = Card.create(user_id: user02.id, name: "Light Dragonite", card_number: 14, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/14_hires.png", quantity: 0, rarity: "holo", notes: "")
card387 = Card.create(user_id: user02.id, name: "Light Togetic", card_number: 15, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/15_hires.png", quantity: 0, rarity: "holo", notes: "")
card388 = Card.create(user_id: user02.id, name: "Miracle Energy", card_number: 16, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/16_hires.png", quantity: 0, rarity: "holo", notes: "")
card389 = Card.create(user_id: user02.id, name: "Shining Celebi", card_number: 106, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/106_hires.png", quantity: 0, rarity: "holo", notes: "")
card390 = Card.create(user_id: user02.id, name: "Shining Charizard", card_number: 107, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/107_hires.png", quantity: 0, rarity: "holo", notes: "")
card391 = Card.create(user_id: user02.id, name: "Shining Kabutops", card_number: 108, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/108_hires.png", quantity: 0, rarity: "holo", notes: "")
card392 = Card.create(user_id: user02.id, name: "Shining Mewtwo", card_number: 109, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/109_hires.png", quantity: 0, rarity: "holo", notes: "")
card393 = Card.create(user_id: user02.id, name: "Shining Noctowl", card_number: 110, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/110_hires.png", quantity: 0, rarity: "holo", notes: "")
card394 = Card.create(user_id: user02.id, name: "Shining Raichu", card_number: 111, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/111_hires.png", quantity: 0, rarity: "holo", notes: "")
card395 = Card.create(user_id: user02.id, name: "Shining Steelix", card_number: 112, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/112_hires.png", quantity: 0, rarity: "holo", notes: "")
card396 = Card.create(user_id: user02.id, name: "Shining Tyranitar", card_number: 113, set: "Neo Destiny", image: "https://images.pokemontcg.io/neo4/113_hires.png", quantity: 0, rarity: "holo", notes: "")

print "Done!"