print "Seeding..."

user01 = User.create(username: "Shu", password: "123")
user02 = User.create(username: "Argoo", password: "123")

card01 = Card.create(user_id: user01.id, name: "Alakazam", set: "base", image: "https://images.pokemontcg.io/base1/1_hires.png", owned: true, quantity: 2, notes: "Non-shadowless, NM condition for both.")
card02 = Card.create(user_id: user01.id, name: "Blastoise", set: "base", image: "https://images.pokemontcg.io/base1/2_hires.png", owned: true, quantity: 3, notes: "Non-shadowless, one stage-error, NM condition.")
card03 = Card.create(user_id: user01.id, name: "Chansey", set: "base", image: "https://images.pokemontcg.io/base1/3_hires.png", owned: true, quantity: 6, notes: "One shadowless, one damaged (crease), rest shadowed and fine.")
card04 = Card.create(user_id: user01.id, name: "Charizard", set: "base", image: "https://images.pokemontcg.io/base1/4_hires.png", owned: true, quantity: 2, notes: "Not for trade yet.")
card05 = Card.create(user_id: user01.id, name: "Clefairy", set: "base", image: "https://images.pokemontcg.io/base1/5_hires.png", owned: true, quantity: 1, notes: "Need a second one.")
card06 = Card.create(user_id: user01.id, name: "Gyarados", set: "base", image: "https://images.pokemontcg.io/base1/6_hires.png", owned: true, quantity: 2, notes: "Shadowed, NM condition.")
card07 = Card.create(user_id: user01.id, name: "Hitmonchan", set: "base", image: "https://images.pokemontcg.io/base1/7_hires.png", owned: true, quantity: 4, notes: "One shadowless, first edition LP condition. Rest shadowed.")
card08 = Card.create(user_id: user01.id, name: "Machamp", set: "base", image: "https://images.pokemontcg.io/base1/8_hires.png", owned: true, quantity: 5, notes: "One shadowless, one not for trade due to sentimental value.")
card09 = Card.create(user_id: user01.id, name: "Magneton", set: "base", image: "https://images.pokemontcg.io/base1/9_hires.png", owned: true, quantity: 5, notes: "One shadowless first edition not for trade, two shadowed for trade, NM condition.")
card10 = Card.create(user_id: user01.id, name: "Mewtwo", set: "base", image: "https://images.pokemontcg.io/base1/10_hires.png", owned: true, quantity: 2, notes: "Shadowed.")
card11 = Card.create(user_id: user01.id, name: "Nidoking", set: "base", image: "https://images.pokemontcg.io/base1/11_hires.png", owned: true, quantity: 4, notes: "Two shadowless for trade, MP condition.")
card12 = Card.create(user_id: user01.id, name: "Ninetales", set: "base", image: "https://images.pokemontcg.io/base1/12_hires.png", owned: true, quantity: 3, notes: "One shadowless for trade, MP condition.")
card13 = Card.create(user_id: user01.id, name: "Poliwrath", set: "base", image: "https://images.pokemontcg.io/base1/13_hires.png", owned: true, quantity: 2, notes: "Shadowed.")
card14 = Card.create(user_id: user01.id, name: "Raichu", set: "base", image: "https://images.pokemontcg.io/base1/14_hires.png", owned: true, quantity: 2, notes: "Shadowed.")
card15 = Card.create(user_id: user01.id, name: "Venusaur", set: "base", image: "https://images.pokemontcg.io/base1/15_hires.png", owned: true, quantity: 3, notes: "One shadowed with blue splotch error for trade.")
card16 = Card.create(user_id: user01.id, name: "Zapdos", set: "base", image: "https://images.pokemontcg.io/base1/16_hires.png", owned: true, quantity: 2, notes: "Shadowed.")

card17 = Card.create(user_id: user02.id, name: "Alakazam", set: "base", image: "https://images.pokemontcg.io/base1/1_hires.png", owned: true, quantity: 1, notes: "meh")
card18 = Card.create(user_id: user02.id, name: "Blastoise", set: "base", image: "https://images.pokemontcg.io/base1/2_hires.png", owned: false, quantity: 0, notes: "want")
card19 = Card.create(user_id: user02.id, name: "Chansey", set: "base", image: "https://images.pokemontcg.io/base1/3_hires.png", owned: true, quantity: 1, notes: "done")
card20 = Card.create(user_id: user02.id, name: "Charizard", set: "base", image: "https://images.pokemontcg.io/base1/4_hires.png", owned: false, quantity: 0, notes: "want more")
card21 = Card.create(user_id: user02.id, name: "Clefairy", set: "base", image: "https://images.pokemontcg.io/base1/5_hires.png", owned: true, quantity: 1, notes: "bad condition")
card22 = Card.create(user_id: user02.id, name: "Gyarados", set: "base", image: "https://images.pokemontcg.io/base1/6_hires.png", owned: false, quantity: 0, notes: "want")
card23 = Card.create(user_id: user02.id, name: "Hitmonchan", set: "base", image: "https://images.pokemontcg.io/base1/7_hires.png", owned: true, quantity: 1, notes: "good condition")
card24 = Card.create(user_id: user02.id, name: "Machamp", set: "base", image: "https://images.pokemontcg.io/base1/8_hires.png", owned: false, quantity: 0, notes: "want")
card25 = Card.create(user_id: user02.id, name: "Magneton", set: "base", image: "https://images.pokemontcg.io/base1/9_hires.png", owned: true, quantity: 1, notes: "selling")
card26 = Card.create(user_id: user02.id, name: "Mewtwo", set: "base", image: "https://images.pokemontcg.io/base1/10_hires.png", owned: false, quantity: 0, notes: "want")
card27 = Card.create(user_id: user02.id, name: "Nidoking", set: "base", image: "https://images.pokemontcg.io/base1/11_hires.png", owned: true, quantity: 1, notes: "no trade, selling")
card28 = Card.create(user_id: user02.id, name: "Ninetales", set: "base", image: "https://images.pokemontcg.io/base1/12_hires.png", owned: false, quantity: 0, notes: "want")
card29 = Card.create(user_id: user02.id, name: "Poliwrath", set: "base", image: "https://images.pokemontcg.io/base1/13_hires.png", owned: true, quantity: 1, notes: "trading, no selling")
card30 = Card.create(user_id: user02.id, name: "Raichu", set: "base", image: "https://images.pokemontcg.io/base1/14_hires.png", owned: false, quantity: 0, notes: "want")
card31 = Card.create(user_id: user02.id, name: "Venusaur", set: "base", image: "https://images.pokemontcg.io/base1/15_hires.png", owned: true, quantity: 1, notes: "good")
card32 = Card.create(user_id: user02.id, name: "Zapdos", set: "base", image: "https://images.pokemontcg.io/base1/16_hires.png", owned: false, quantity: 0, notes: "want")

print "Done!"